In [10]:

def odd(x):
    for i in x:
        if i%2!=0:
            print(i)
odd(range(1,30))            
                   
          

        

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29


In [19]:
odd_num=[i for i in range(10,30) if i%2!=0 ]
print(odd_num)

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


### numpy 
this introduces multidimensional(ND arrays) which we know as lists in python.This adds new methods to manipulate arrays which are not in python lists.
Numpy also makes it easier to identify and work with null values

In [ ]:
import numpy as np

In [21]:
import pandas as pd

In [42]:
ls1=[[16,45,30,6,5],[6,None,8,70,8],[11,67,9,40,7]]

In [24]:
ls1[1][2]

8

In [43]:
arr=np.array(ls1)

In [44]:
arr

array([[16, 45, 30, 6, 5],
       [6, None, 8, 70, 8],
       [11, 67, 9, 40, 7]], dtype=object)

In [28]:
ls1.count

<function list.count(value, /)>

In [37]:
arr.size

15

In [82]:
arr1=np.array(ls1, dtype=np.float)


In [83]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [84]:
arr2=arr1.copy()

In [85]:
arr2[np.isnan(arr1)]=0

In [86]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6.,  0.,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [87]:
arr2[1][1]=(np.sum(arr2)/arr2.size)

In [88]:
arr2

array([[16.        , 45.        , 30.        ,  6.        ,  5.        ],
       [ 6.        , 21.86666667,  8.        , 70.        ,  8.        ],
       [11.        , 67.        ,  9.        , 40.        ,  7.        ]])

In [89]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])